version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - project_network

  api:
    build: ./api
    ports:
      - "${API_PORT}:5000"
    env_file:
      - .env  # ✅ Load environment variables at runtime
    depends_on:
      database:
        condition: service_healthy  # ✅ Ensures DB is ready before starting API
    networks:
      - project_network

  database:
    image: mysql:8.0  # ✅ Using official MySQL image
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env  # ✅ Loads database credentials from .env
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persistent database storage
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - project_network

networks:
  project_network:
    driver: bridge  # ✅ Isolate services for better security

volumes:
  mysql_data:  # ✅ Persistent volume for database
