version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - project_network
    restart: unless-stopped  # ✅ Ensures frontend restarts if it crashes

  api:
    build: ./api
    ports:
      - "${API_PORT}:5000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy  # ✅ Ensures MySQL is fully ready before API starts
    networks:
      - project_network
    restart: unless-stopped  # ✅ Keeps API running if it crashes

  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persistent database storage
      - ./database/my.cnf:/etc/mysql/my.cnf  # ✅ Load custom MySQL config
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ Auto-run SQL script only on first start
    command: --default-authentication-plugin=mysql_native_password  # ✅ Fix MySQL authentication issues
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$DATABASE_USER", "-p$DATABASE_PASSWORD"]
      interval: 10s
      retries: 5
    networks:
      - project_network

networks:
  project_network:
    driver: bridge  # ✅ Isolates services for better security

volumes:
  mysql_data:  # ✅ Persistent MySQL storage
