version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - project_network

  api:
    build: ./api
    ports:
      - "${API_PORT}:5000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - project_network

  database:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql  # ✅ Persistent database storage
      - ./database/my.cnf:/etc/mysql/my.cnf  # ✅ Load custom MySQL config
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ Auto-run SQL script on first start
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  mysql_data:
